# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created or push to master with code change in src folder or manual trigger
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/npm-publish.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && !(github.ref == 'refs/heads/master' && contains(github.event.head_commit.message, '[publish'))
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build

  publish-npm:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && (github.event_name != 'push' || contains(github.event.head_commit.message, '[publish]'))
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Install
        run: npm ci
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-npm-beta:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push' && contains(github.event.head_commit.message, '[publish-beta]')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Install
        run: npm ci
      - name: Publish
        run: npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
